# Generated by Django 5.1.2 on 2024-10-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_taskitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='recently_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
